name: Test

on: [push, pull_request]

jobs:
  tests-with-token:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login == 'axel-op'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [8, 11, 16]
        version: ["1.6", ""]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - uses: ./
        with:
          skip-commit: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.version }}

  tests-without-token:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [8, 11]
        version: ["1.6", ""]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - uses: ./
        continue-on-error: ${{ matrix.os == 'macos-latest' }}
        with:
          skip-commit: true
          version: ${{ matrix.version }}
